### PR TITLE
Implement Commitizen

### LINKED ISSUE #17: Adopt Commitizen and Conventional Commits for the Mentor Portal
# Overview

This project should adopt the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec to standardize commit messages and make them more consistent. Additionally, this project should adopt [Commitizen](https://github.com/commitizen/cz-cli) installed as a dev dependency to the repo to make adopting Conventional Commits easier.

# Tasks

- [ ] Set up Commitizen using the same configuration as [HackPortal](https://github.com/acmutd/hackportal)
- [ ] Have Git hooks to run commitizen on commit
- [ ] Update README to include information on making good commits
  - [ ] Also strongly recommend contributors to read [this guide](https://chris.beams.io/posts/git-commit/) on how to write a good commit message

### PR DESCRIPTION
**Pull request by WillieCubed**
Closes #17

This PR initializes Commitizen for this repository and requires all commits to follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) format.

### CODE REVIEW

**Review by NickBurnett — APPROVED** [review]
ill allow it

**Review by stevenmqnguyen — APPROVED** [review]
Now samesies for portal

**Comment by WillieCubed** [comment]
Hmm, it turns out we're missing the most important aspect of these changes: they need to run on each commit via Husky, and the configuration doesn't match HackPortal's.

**Comment by abdullah50053** [comment]
Pls make a meaningful commit before opening a PR 💯

**Pull request closed without merging**
